name: PRFAQ

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}


jobs:
  get_pr_stats:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: GitHub GraphQL Action
      uses: helaili/github-graphql-action@2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        query: queries/pr_stats.yaml
        logLevel: debug
        outputFile: pr_stats.json
        pr_num: ${{ env.PR_NUMBER }}
    - name: Render template
      id: template
      uses: chuhlomin/render-template@v1.2
      with:
        template: templates/prfaq-template.md
        vars: |
          foo: this
          bar: that
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ env.PR_NUMBER }}
        body: ${{ steps.template.outputs.result }}     